### PR TITLE
remove python path

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
cc @seanyen i added you to this recipe, too.

**Comment by seanyen** [comment]
Just wondering, is it required to fix all the path issues from `catkin` by patching the code? I am under an impression that `conda` will fix up any hard-coded paths automatically or with some hints. Isn't it  sufficient for `ROS` case (https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html)?

**Comment by wolfv** [comment]
- the python path definitely does not seem to be necessary
- `CMAKE_PREFIX_PATH` is necessary for catkin to work. However, since this activation script does not reside in the root of the environment, I had to patch it so that it doesn't add it's own location to the `CMAKE_PREFIX_PATH`
- `LD_LIBRARY_PATH` I had the experience that some native python extensions are not properly loaded when it's not set, but it might not be necessary ... we can check that once we have the base ready. I had to remove that path from OS X as native libraries such as SQLite were not found anymore and the whole conda env basically broke :)
- `PATH` could be removed as conda already sets it
- `PKG_CONFIG_PATH` .. not sure wether conda sets it or not

now, re-reading your question, i think i got it wrong. you're right, conda does make packages relocatable. but overriding some of these environment variables causes bad things to happen. 
I just run into the problem with the python path for the last two recipes on staged recipes because some package requires `enum34` and that "breaks" python 3.7 and setting the `PYTHONPATH` somehow makes 3.7 load the regex module from 2.7 ... 

Also one other note is that these scripts are executed automatically when doing `conda activate my_ros_env`. I should probably add the appropriate deactivation script as well for clearing the catkin-set variables.

**Comment by wolfv** [comment]
btw just because you were working on the `ogre` recipe: RViz hits one of the tricky problems with relocatability.

In these lines:
https://github.com/ros-visualization/rviz/blob/e49a5448f2a763dcba2963a7e87e627b6db6d1b6/src/rviz/env_config.cpp.in#L48-L53

They hardcode the path, and then place it in a `std::string`. Optimizing compilers and the small buffer optimization make this very tricky though, because the compiler inlines the hardcoded string and the replacement of the string in the binaries doesn't work. (ref https://github.com/conda/conda-build/issues/1674)

I tried a couple of tricks to force the compiler to not inline / optimize out this variable but eventually I used `sys::getenv('CONDA_PREFIX')` which is quite bad because then RViz would only run from this environment when the environment is activated. So once I get to RViz i might need to find another trick :)

Just wanted to let you know in case you come across that.

**Pull request merged**
